config/routes.rb
Rails.application.routes.draw do
  resources :icecreams

  get 'welcome/index'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/icecream.rb
class Icecream < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/icecreams_controller.rb
class IcecreamsController < ApplicationController
  before_action :find_icecream, only: [:show, :edit, :updade, :destroy]

  def index
		@icecream = Icecream.all.order("created_at DESC")
	end

  def show
  end

  def new
    @icecream = Icecream.new
  end

  def create
    @icecream = Icecream.new(icecream_params)

    if @icecream.save
      redirect_to @icecream, notice: "Sorvete salvo com sucesso!"
    else
      render 'new'
    end

  end

  private

  def icecream_params
    params.require(:icecream).permit(:title, :description)
  end

  def find_icecream
    @icecream = Icecream.find(params[:id])
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/icecreams_helper.rb
module IcecreamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/icecreams/_form.html.haml
= simple_form_for @icecream do |f|
  = f.input :title
  = f.input :description
  = f.button :submit, class: "button"

app/views/icecreams/index.html.haml
%h1 This is the test for Ice Cream

app/views/icecreams/new.html.haml
.wrapper_with_padding
  %h1 Adicionar Sorvete

  = render 'form'

= link_to "Voltar", root_path, class: 'btn btn-default'

app/views/icecreams/show.html.haml
.wrapper_with_padding
  #note_show
    %h1.title= @icecream.title
    %p= simple_format(@icecream.description)

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Perruci | Sorvete Artesanal
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  %link{:rel => "stylesheet", :href => "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"}
  = csrf_meta_tags
%body
  %header
    .header_inner
      = link_to image_tag('logo.svg'), root_path, id: "logo"
      %nav
        = link_to "Sorvetes", icecreams_path
        = link_to "Sobre"
        = link_to "Contato"

  %p.notice= notice
  %p.alert= alert

  = yield

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 Perruci
    %p Sorvetes Artesanais    

#testimonial
  .wapper
    %p.quote "The greatest notebook application. Period"
    %p.name - Malcon Moura de Lima

#callouts
  .callouts_inner
    .wrapper
      .callout
        %i.fa.fa-btc
        %h2 Bitcoin
        %p Cevadis im ampola pa arma uma pindureta. Delegadis gente finis, bibendum egestas augue arcu ut est. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose.
      .callout
        %i.fa.fa-phone
        %h2 Contato
        %p Cevadis im ampola pa arma uma pindureta. Delegadis gente finis, bibendum egestas augue arcu ut est. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose.
      .callout
        %i.fa.fa-info
        %h2 Informações
        %p Produzimos e entregamos sorvete artesanal em domicílio na cidade de João Pessoa - PB

#bottom_cta
  .wrapper
    %h2 Sorvete Perruci
    %p Produzimos e entregamos sorvete artesanal em domicílio na cidade de João Pessoa - PB

%footer
  %p &copy; Malsay